image: gitpod/workspace-dotnet

tasks:
  - init: dotnet tool install --tool-path .paket Paket && export PATH=.paket:$PATH

vscode:
  extensions:
    - ms-vscode.csharp@1.21.1-beta1:n3X5MLk7F4gtlOJON1hmQQ==
    - georgewfraser.fsharp-language-server@0.1.26:xXGsmZPt2bSdRTECYgQbvQ==